{% set name = "freegenes" %}
{% set version = "0.0.11" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 58254cc9fcc0081ab3dc87028a9aeb3d092bde9734ef114458642e52e884e8a0

build:
  number: 0
  entry_points:
    - freegenes=freegenes.client:main
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv "
  noarch: python

requirements:
  host:
    - pip
    - python >=3
    - setuptools
    - pytest-runner
  run:
    - python >=3.6
    - requests >=2.21.0
    - semver >=2.8.0

test:
  imports:
    - freegenes
    - freegenes.main
    - freegenes.client
    - freegenes.client.shell
    - freegenes.logger
    - freegenes.logger.message
    - freegenes.logger.spinner
    - freegenes.tests
  commands:
    - freegenes --help

about:
  home: https://vsoch.github.io/freegenes-python
  license: MPL-2.0
  license_family: OTHER
  license_file: LICENSE
  summary: Python API Client for FreeGenes Node
  doc_url: https://vsoch.github.io/freegenes-python
  dev_url: https://github.com/vsoch/freegenes-python

extra:
  recipe-maintainers:
    - vsoch
    - Koeng101
