travis:
  secure:
    BINSTAR_TOKEN: j4HwsCRjeO5PjjFCwaNy8dqZOFksx2SF9y40+G8uR7ngUg6aodlve+ruBl4eIZeeP+NW33KYgEptrxvIVBp/CXeNkT+aES17iIxh17fOuG9y8Ktsa0tpTBYOfEYj2RCZpNsfxd06VbC2HqDtdNGfm8Cdrl7F8BfeEXtWFUi0O/8kEKo1VcNwo0cZSpulFYCEWewR4itaFVDYXITHFVjHeKxHwzjJIt9WBXuNUzhFZBBTXJl5KTi4fsGvOqK6pgoYxcwozwhUfu2KfWL+FaUp7LB/MhdYTPjuTta3i8u5vImqpqTrY9Q1+Q0KLDECnEZSVIXVWRvnITTZPaqrvza7E4z1HRb5t62bzX3rBJMGQx0gCwDCV8IlkBykaS71LLeK9rAjEzTi64MulS03lq99jXG+w2GiI3RnI84hulYomGRh69reXndlf2+/shEQrFSwZ9lfRO+Lp2l+ivtwifYUD4PMZmVEqLAsrl+iJvlOPvNhCjsZEtx96oWenaEtpUMwuVOSdUhH0yFYXYsSlje88+sdxj0It9D4MyXTmSDxlkE4RxSjal5im+TQNFL51IfwwMveqPESgZwFBeA3g+v7o1ptS5iSWG4T7lK8XEvaGH52Jfwh7eKL2SXdsPj1qqn6b9ZuiVTRJrlC38VtbKZK3DAFrK3aZ8qF2zTkWkpTT9w=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
